version: '3.3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8877:5011
    volumes:
      - .:/opt/app
    environment:
      DEV: 'True'
    # env_file: local.env
