version: '3.8'

services:
  # Common params between `dev` and `deploy`
  deploy: &common
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8877:5011
    environment:
      DEV: 'True'
    # env_file: local.env
    command: ["bash"]
  dev:
    <<: *common
    volumes:
      - .:/opt/app

